In [1]:
import numpy as np

In [2]:
from utils.SPPTD import SimWorkers, CATD, S0, S1

In [3]:
vworkers = SimWorkers(5, 6, 8) # K=5, M=6, 稀疏度为 0.8

In [4]:
[S0_Data, S1_Data] = vworkers.ss()

In [5]:
catd1 = CATD(vworkers.PHI, vworkers.XM)

In [6]:
XT_INIT = np.sum(vworkers.XM, axis = 0) / np.sum(vworkers.PHI, axis = 0)

In [7]:
wt = catd1.up_weight(XT_INIT)
print(wt)

[0.03977766 0.02457449 0.00721653 0.08261904 0.02392657]


In [8]:
xt = catd1.up_truth(wt)

In [9]:
xt

array([4.0129081 , 3.80794781, 1.05300785, 5.11849004, 5.0025962 ,
       3.58995003])

In [10]:
s0 = S0(5, 6, *S0_Data)

In [11]:
[C0, C_pack1] = s0.pre_up_weight()

In [12]:
s1 = S1(5, 6, C0, C_pack1, s0.pk, *S1_Data)

In [13]:
C = s1.up_weight(XT_INIT)

In [14]:
C_pack2 = s0.up_truth(C)

In [15]:
[C5, C6] = s1.up_truth(C_pack2)

In [16]:
s0.resolve_xt(C5, C6)

[4.012908101693612,
 3.807947811627186,
 1.053007851369048,
 5.1184900436315415,
 5.002596196040304,
 3.58995003011946]

In [17]:
s0.tw

array([0.03977766, 0.02457449, 0.00721653, 0.08261904, 0.02392657])