In [7]:
# !! 实验现场，注意安全
# 测试内容： Accuracy
# 固定 M = 20, K: [4, 10], S: [4, 8]
import numpy as np
import random
from utils.SPPTD import SimWorkers, CATD, S0, S1

In [8]:
def RMSE(e_x, t_x):
    mse = (np.sum((np.array(e_x) - np.array(t_x)) ** 2)) / M
    return mse ** 0.5

In [11]:
def TEST(K, M, S):
    res = [[], []]
    ground_truth = [int(random.random() * 100) for m in range(M)]
    vw = SimWorkers(K, M, S, ground_truth)
    [S0_Data, S1_Data] = vw.ss()
    catd = CATD(vw.PHI, vw.XM)
    init_truth = [int(random.random() * 100) for m in range(M)]
    x = init_truth
    for i in range(3):
        w = catd.up_weight(x)
        x = catd.up_truth(w)
    res1 = RMSE(x, ground_truth)
    s0 = S0(K, M, *S0_Data)
    [C0, C_pack1] = s0.pre_up_weight()
    s1 = S1(K, M, C0, C_pack1, s0.pk, *S1_Data)
    x = init_truth
    for i in range(3):
        C = s1.up_weight(x)
        C_pack2 = s0.up_truth(C)
        [C5, C6] = s1.up_truth(C_pack2)
        x = s0.resolve_xt(C5, C6)
    res2 = RMSE(x, ground_truth)
    return [res1, res2]

In [4]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 20; S = 4
# T = 3
time1 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 11):
        [res1, res2] = TEST(K, M, S)
        time1[t][0].append(res1)
        time1[t][1].append(res2)
print((np.array(time1[0]) + np.array(time1[1]) + np.array(time1[2])) / 3)

[[2.10932198 1.56427725 1.47483613 1.65492491 1.08917389 1.35215479]
 [2.10932198 1.56427725 1.47483613 1.65492491 1.08917389 1.35215479]]


In [5]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 20; S = 6
time2 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 11):
        [res1, res2] = TEST(K, M, S)
        time2[t][0].append(res1)
        time2[t][1].append(res2)
print((np.array(time2[0]) + np.array(time2[1]) + np.array(time2[2])) / 3)

[[1.64880631 1.26675877 1.41619916 1.05010103 0.9692497  1.11580332]
 [1.64880631 1.26675877 1.41619916 1.05010103 0.9692497  1.11580332]]


In [6]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 20; S = 8
time3 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 11):
        [res1, res2] = TEST(K, M, S)
        time3[t][0].append(res1)
        time3[t][1].append(res2)
print((np.array(time3[0]) + np.array(time3[1]) + np.array(time3[2])) / 3)

[[1.14216401 1.17892883 1.1510717  0.81211172 0.73967593 0.71549794]
 [1.14216401 1.17892883 1.1510717  0.81211172 0.73967593 0.71549794]]


In [12]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 20; S = 8
time3 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 26, 5):
        [res1, res2] = TEST(K, M, S)
        time3[t][0].append(res1)
        time3[t][1].append(res2)
print((np.array(time3[0]) + np.array(time3[1]) + np.array(time3[2])) / 3)

[[1.0569453  0.76821125 0.57528271 0.58965629 0.51362287]
 [1.0569453  0.76821125 0.57528271 0.58965629 0.51362287]]


In [13]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 20; S = 6
time3 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 26, 5):
        [res1, res2] = TEST(K, M, S)
        time3[t][0].append(res1)
        time3[t][1].append(res2)
print((np.array(time3[0]) + np.array(time3[1]) + np.array(time3[2])) / 3)

[[1.35062592 1.09802551 0.81992735 0.59096782 0.58860828]
 [1.35062592 1.09802551 0.81992735 0.59096782 0.58860828]]


In [14]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 20; S = 4
time3 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 26, 5):
        [res1, res2] = TEST(K, M, S)
        time3[t][0].append(res1)
        time3[t][1].append(res2)
print((np.array(time3[0]) + np.array(time3[1]) + np.array(time3[2])) / 3)

[[1.74746358 1.54445824 0.80215272 0.7413175  0.75015319]
 [1.74746358 1.54445824 0.80215272 0.7413175  0.75015319]]
