In [1]:
# !! 实验现场，注意安全
# 测试内容： Accuracy
# 固定 M = 20, K: [4, 10], S: [4, 8]
import numpy as np
import random
from utils.SPPTD import SimWorkers, CATD, S0, S1

In [2]:
def RMSE(e_x, t_x):
    mse = (np.sum((np.array(e_x) - np.array(t_x)) ** 2)) / M
    return mse ** 0.5

In [3]:
def TEST(K, M, S):
    res = [[], []]
    ground_truth = [int(random.random() * 100) for m in range(M)]
    vw = SimWorkers(K, M, S, ground_truth)
    [S0_Data, S1_Data] = vw.ss()
    catd = CATD(vw.PHI, vw.XM)
    init_truth = [int(random.random() * 100) for m in range(M)]
    x = init_truth
    for i in range(4):
        w = catd.up_weight(x)
        x = catd.up_truth(w)
    res1 = RMSE(x, ground_truth)
    s0 = S0(K, M, *S0_Data)
    [C0, C_pack1] = s0.pre_up_weight()
    s1 = S1(K, M, C0, C_pack1, s0.pk, *S1_Data)
    x = init_truth
    for i in range(4):
        C = s1.up_weight(x)
        C_pack2 = s0.up_truth(C)
        [C5, C6] = s1.up_truth(C_pack2)
        x = s0.resolve_xt(C5, C6)
    res2 = RMSE(x, ground_truth)
    return [res1, res2]

In [4]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 10; S = 8
# T = 3
time1 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 11):
        [res1, res2] = TEST(K, M, S)
        time1[t][0].append(res1)
        time1[t][1].append(res2)
print((np.array(time1[0]) + np.array(time1[1]) + np.array(time1[2])) / 3)

[[1.34503202 1.11532687 0.88241602 0.85073516 0.94509463 0.76737024]
 [1.34503202 1.11532687 0.88241602 0.85073516 0.94509463 0.76737024]]


In [5]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 10; S = 6
time2 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 11):
        [res1, res2] = TEST(K, M, S)
        time2[t][0].append(res1)
        time2[t][1].append(res2)
print((np.array(time2[0]) + np.array(time2[1]) + np.array(time2[2])) / 3)

[[1.4535625  1.168124   1.31382401 1.31112801 1.39539005 0.87449351]
 [1.4535625  1.168124   1.31382401 1.31112801 1.39539005 0.87449351]]


In [6]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 10; S = 8
time3 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 11):
        [res1, res2] = TEST(K, M, S)
        time3[t][0].append(res1)
        time3[t][1].append(res2)
print((np.array(time3[0]) + np.array(time3[1]) + np.array(time3[2])) / 3)

[[1.40237003 1.25430579 0.91898025 1.00437945 0.99632894 0.8322668 ]
 [1.40237003 1.25430579 0.91898025 1.00437945 0.99632894 0.8322668 ]]


In [7]:
# 设定 workers 数量， objects 数量，以及稀疏度
M = 10; S = 4
time4 = [[[], []], [[], []], [[], []]]
for t in range(3):
    for K in range(5, 11):
        [res1, res2] = TEST(K, M, S)
        time4[t][0].append(res1)
        time4[t][1].append(res2)
print((np.array(time4[0]) + np.array(time4[1]) + np.array(time4[2])) / 3)

/home/liu/git_repo/SPPTD_TEST/utils/SPPTD.py:55: RuntimeWarning: divide by zero encountered in true_divide
  W = Y / np.sum(self.PHI * (self.XM - XT) ** 2, axis = 1)
/home/liu/git_repo/SPPTD_TEST/utils/SPPTD.py:58: RuntimeWarning: invalid value encountered in true_divide
  XT = np.dot(W, self.XM) / np.dot(W, self.PHI)


[[2.04189774        nan 1.69957687 1.50306373 1.27538657 1.5802012 ]
 [2.04189774 1.47805562 1.69957687 1.50306373 1.27538657 1.5802012 ]]
