In [1]:
from phe import paillier

In [2]:
import random

In [3]:
import scipy.stats

In [4]:
import numpy as np

In [5]:
K = 6; M = 5; S = 5

In [6]:
XM = np.zeros([K, M])

In [7]:
PHI = np.zeros([K, M])

In [8]:
SPL = [1] * S + [0] * (10 - S)

In [9]:
pk, sk = paillier.generate_paillier_keypair()

In [10]:
for k in range(K):
    PHI[k] = [random.choice(SPL) for m in range(M)]
for i in np.sum(PHI, axis = 0):
    assert i > 0

In [11]:
for k in range(K):
    for m in range(M):
        XM[k][m] = PHI[k][m] * round((random.random())*10, 2)

In [12]:
Y = np.array([scipy.stats.chi2.ppf(0.05, k) for k in np.sum(PHI, axis = 1)])

In [13]:
np.sum(XM, axis = 0) / np.sum(PHI, axis = 0)

array([7.97  , 5.475 , 1.91  , 3.9275, 4.71  ])

In [14]:
truth = np.array([round((random.random())*10, 2) for m in range(M)])

In [15]:
W = Y / np.sum(PHI * (XM - truth) ** 2, axis = 1)

In [16]:
W

array([0.00641426, 0.00900752, 0.00297667, 0.00010164, 0.00842603,
       0.00253005])

In [17]:
np.dot(W.T, XM) / np.dot(W.T, PHI)

array([8.04969552, 6.20343618, 1.91      , 3.18643267, 3.69202943])

In [18]:
# 加密权重更新
# PHI = phi0 + phi1
# XM = xm0 + xm1

In [19]:
tphi = [ PHI[k] / Y[k] for k in range(K)]

In [20]:
tphi0 = [[] for k in range(K)]
phi0 = [[] for k in range(K)]
xm0 = [[] for k in range(K)]
for k in range(K):
    tphi0[k] = [ round(random.random(),2) for m in range(M)]
    phi0[k] = [ round(random.random(),2) for m in range(M)]
    xm0[k] = [ round(random.random(),2) for m in range(M)]
tphi0 = np.array(tphi0)
phi0 = np.array(phi0)
xm0 = np.array(xm0)

In [21]:
tphi1 = tphi - tphi0
phi1 = PHI - phi0
xm1 = XM - xm0

In [22]:
C0 = np.sum(tphi0 * (xm0 ** 2), axis = 1)

In [23]:
C1 = np.sum(tphi1 * (xm0 ** 2), axis = 1)

In [24]:
# C2 = np.sum(2 * tphi * xm0 * (xm1 - truth), axis = 1)

In [25]:
C2 = np.sum(np.multiply(2, tphi) * xm0 * (xm1 - truth), axis = 1)

In [26]:
C3 = np.sum(tphi0 * (xm1 - truth) ** 2, axis = 1)

In [27]:
C4 = np.sum(tphi1 * (xm1 - truth) ** 2, axis = 1)

In [28]:
1/ (C0 + C1 + C2 + C3 + C4)

array([0.00641426, 0.00900752, 0.00297667, 0.00010164, 0.00842603,
       0.00253005])

In [29]:
C5 = np.dot(W, XM)

In [30]:
C6 = np.dot(W, PHI)

In [31]:
C5/C6

array([8.04969552, 6.20343618, 1.91      , 3.18643267, 3.69202943])

In [32]:
XM.shape

(6, 5)

In [33]:
XM.reshape(K*M,)

array([0.  , 9.03, 0.  , 7.46, 3.17, 0.  , 2.61, 0.  , 1.76, 2.11, 8.74,
       0.  , 0.  , 6.04, 8.11, 0.  , 2.32, 0.  , 0.  , 0.  , 8.1 , 7.94,
       1.91, 0.45, 0.  , 7.07, 0.  , 0.  , 0.  , 5.45])